name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: Who to greet
        type: string
        required: true
        default: World
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet!
        run: echo "Hello "
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: 
        description: Greeting time
        value: ${{ jobs.reusable-job.outputs.current-time }}
